/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppShipmentsRouteImport } from './routes/app.shipments'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppPartnersRouteImport } from './routes/app.partners'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppDeliveriesRouteImport } from './routes/app.deliveries'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppCartRouteImport } from './routes/app.cart'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppUsersIndexRouteImport } from './routes/app.users.index'
import { Route as AppTrackingIndexRouteImport } from './routes/app.tracking.index'
import { Route as AppShipmentsIndexRouteImport } from './routes/app.shipments.index'
import { Route as AppPaymentsIndexRouteImport } from './routes/app.payments.index'
import { Route as AppPartnersIndexRouteImport } from './routes/app.partners.index'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppMedicinesIndexRouteImport } from './routes/app.medicines.index'
import { Route as AppDeliveriesIndexRouteImport } from './routes/app.deliveries.index'
import { Route as AppTrackingIdRouteImport } from './routes/app.tracking.$id'
import { Route as AppShipmentsIdRouteImport } from './routes/app.shipments.$id'
import { Route as AppPaymentsIdRouteImport } from './routes/app.payments.$id'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as AppMedicinesIdRouteImport } from './routes/app.medicines.$id'
import { Route as AppDeliveriesIdRouteImport } from './routes/app.deliveries.$id'
import { Route as AppMedicinesIdIndexRouteImport } from './routes/app.medicines.$id.index'
import { Route as AppUsersPharmacyIdRouteImport } from './routes/app.users.pharmacy.$id'
import { Route as AppUsersManufacturerIdRouteImport } from './routes/app.users.manufacturer.$id'
import { Route as AppUsersDeliveryIdRouteImport } from './routes/app.users.delivery.$id'
import { Route as AppPartnersTypeIdRouteImport } from './routes/app.partners.$type.$id'
import { Route as AppMedicinesIdHistoryRouteImport } from './routes/app.medicines.$id.history'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppShipmentsRoute = AppShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppTrackingIndexRoute = AppTrackingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTrackingRoute,
} as any)
const AppShipmentsIndexRoute = AppShipmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShipmentsRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPartnersIndexRoute = AppPartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPartnersRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppMedicinesIndexRoute = AppMedicinesIndexRouteImport.update({
  id: '/medicines/',
  path: '/medicines/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesIndexRoute = AppDeliveriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeliveriesRoute,
} as any)
const AppTrackingIdRoute = AppTrackingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTrackingRoute,
} as any)
const AppShipmentsIdRoute = AppShipmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppShipmentsRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppMedicinesIdRoute = AppMedicinesIdRouteImport.update({
  id: '/medicines/$id',
  path: '/medicines/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesIdRoute = AppDeliveriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDeliveriesRoute,
} as any)
const AppMedicinesIdIndexRoute = AppMedicinesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMedicinesIdRoute,
} as any)
const AppUsersPharmacyIdRoute = AppUsersPharmacyIdRouteImport.update({
  id: '/pharmacy/$id',
  path: '/pharmacy/$id',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersManufacturerIdRoute = AppUsersManufacturerIdRouteImport.update({
  id: '/manufacturer/$id',
  path: '/manufacturer/$id',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersDeliveryIdRoute = AppUsersDeliveryIdRouteImport.update({
  id: '/delivery/$id',
  path: '/delivery/$id',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppPartnersTypeIdRoute = AppPartnersTypeIdRouteImport.update({
  id: '/$type/$id',
  path: '/$type/$id',
  getParentRoute: () => AppPartnersRoute,
} as any)
const AppMedicinesIdHistoryRoute = AppMedicinesIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppMedicinesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deliveries': typeof AppDeliveriesRouteWithChildren
  '/app/inventory': typeof AppInventoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/partners': typeof AppPartnersRouteWithChildren
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRouteWithChildren
  '/app/tracking': typeof AppTrackingRouteWithChildren
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/medicines/$id': typeof AppMedicinesIdRouteWithChildren
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/shipments/$id': typeof AppShipmentsIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
  '/app/deliveries/': typeof AppDeliveriesIndexRoute
  '/app/medicines/': typeof AppMedicinesIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/partners/': typeof AppPartnersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/shipments/': typeof AppShipmentsIndexRoute
  '/app/tracking/': typeof AppTrackingIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/medicines/$id/history': typeof AppMedicinesIdHistoryRoute
  '/app/partners/$type/$id': typeof AppPartnersTypeIdRoute
  '/app/users/delivery/$id': typeof AppUsersDeliveryIdRoute
  '/app/users/manufacturer/$id': typeof AppUsersManufacturerIdRoute
  '/app/users/pharmacy/$id': typeof AppUsersPharmacyIdRoute
  '/app/medicines/$id/': typeof AppMedicinesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/shipments/$id': typeof AppShipmentsIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
  '/app/deliveries': typeof AppDeliveriesIndexRoute
  '/app/medicines': typeof AppMedicinesIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/partners': typeof AppPartnersIndexRoute
  '/app/payments': typeof AppPaymentsIndexRoute
  '/app/shipments': typeof AppShipmentsIndexRoute
  '/app/tracking': typeof AppTrackingIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/medicines/$id/history': typeof AppMedicinesIdHistoryRoute
  '/app/partners/$type/$id': typeof AppPartnersTypeIdRoute
  '/app/users/delivery/$id': typeof AppUsersDeliveryIdRoute
  '/app/users/manufacturer/$id': typeof AppUsersManufacturerIdRoute
  '/app/users/pharmacy/$id': typeof AppUsersPharmacyIdRoute
  '/app/medicines/$id': typeof AppMedicinesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deliveries': typeof AppDeliveriesRouteWithChildren
  '/app/inventory': typeof AppInventoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/partners': typeof AppPartnersRouteWithChildren
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRouteWithChildren
  '/app/tracking': typeof AppTrackingRouteWithChildren
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/medicines/$id': typeof AppMedicinesIdRouteWithChildren
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/shipments/$id': typeof AppShipmentsIdRoute
  '/app/tracking/$id': typeof AppTrackingIdRoute
  '/app/deliveries/': typeof AppDeliveriesIndexRoute
  '/app/medicines/': typeof AppMedicinesIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/partners/': typeof AppPartnersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/shipments/': typeof AppShipmentsIndexRoute
  '/app/tracking/': typeof AppTrackingIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/medicines/$id/history': typeof AppMedicinesIdHistoryRoute
  '/app/partners/$type/$id': typeof AppPartnersTypeIdRoute
  '/app/users/delivery/$id': typeof AppUsersDeliveryIdRoute
  '/app/users/manufacturer/$id': typeof AppUsersManufacturerIdRoute
  '/app/users/pharmacy/$id': typeof AppUsersPharmacyIdRoute
  '/app/medicines/$id/': typeof AppMedicinesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/cart'
    | '/app/checkout'
    | '/app/dashboard'
    | '/app/deliveries'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/orders'
    | '/app/partners'
    | '/app/payments'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipments'
    | '/app/tracking'
    | '/app/users'
    | '/app/deliveries/$id'
    | '/app/medicines/$id'
    | '/app/orders/$id'
    | '/app/payments/$id'
    | '/app/shipments/$id'
    | '/app/tracking/$id'
    | '/app/deliveries/'
    | '/app/medicines/'
    | '/app/orders/'
    | '/app/partners/'
    | '/app/payments/'
    | '/app/shipments/'
    | '/app/tracking/'
    | '/app/users/'
    | '/app/medicines/$id/history'
    | '/app/partners/$type/$id'
    | '/app/users/delivery/$id'
    | '/app/users/manufacturer/$id'
    | '/app/users/pharmacy/$id'
    | '/app/medicines/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/cart'
    | '/app/checkout'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/deliveries/$id'
    | '/app/orders/$id'
    | '/app/payments/$id'
    | '/app/shipments/$id'
    | '/app/tracking/$id'
    | '/app/deliveries'
    | '/app/medicines'
    | '/app/orders'
    | '/app/partners'
    | '/app/payments'
    | '/app/shipments'
    | '/app/tracking'
    | '/app/users'
    | '/app/medicines/$id/history'
    | '/app/partners/$type/$id'
    | '/app/users/delivery/$id'
    | '/app/users/manufacturer/$id'
    | '/app/users/pharmacy/$id'
    | '/app/medicines/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/cart'
    | '/app/checkout'
    | '/app/dashboard'
    | '/app/deliveries'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/orders'
    | '/app/partners'
    | '/app/payments'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipments'
    | '/app/tracking'
    | '/app/users'
    | '/app/deliveries/$id'
    | '/app/medicines/$id'
    | '/app/orders/$id'
    | '/app/payments/$id'
    | '/app/shipments/$id'
    | '/app/tracking/$id'
    | '/app/deliveries/'
    | '/app/medicines/'
    | '/app/orders/'
    | '/app/partners/'
    | '/app/payments/'
    | '/app/shipments/'
    | '/app/tracking/'
    | '/app/users/'
    | '/app/medicines/$id/history'
    | '/app/partners/$type/$id'
    | '/app/users/delivery/$id'
    | '/app/users/manufacturer/$id'
    | '/app/users/pharmacy/$id'
    | '/app/medicines/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shipments': {
      id: '/app/shipments'
      path: '/shipments'
      fullPath: '/app/shipments'
      preLoaderRoute: typeof AppShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/partners': {
      id: '/app/partners'
      path: '/partners'
      fullPath: '/app/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deliveries': {
      id: '/app/deliveries'
      path: '/deliveries'
      fullPath: '/app/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/tracking/': {
      id: '/app/tracking/'
      path: '/'
      fullPath: '/app/tracking/'
      preLoaderRoute: typeof AppTrackingIndexRouteImport
      parentRoute: typeof AppTrackingRoute
    }
    '/app/shipments/': {
      id: '/app/shipments/'
      path: '/'
      fullPath: '/app/shipments/'
      preLoaderRoute: typeof AppShipmentsIndexRouteImport
      parentRoute: typeof AppShipmentsRoute
    }
    '/app/payments/': {
      id: '/app/payments/'
      path: '/'
      fullPath: '/app/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/partners/': {
      id: '/app/partners/'
      path: '/'
      fullPath: '/app/partners/'
      preLoaderRoute: typeof AppPartnersIndexRouteImport
      parentRoute: typeof AppPartnersRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/app/medicines/': {
      id: '/app/medicines/'
      path: '/medicines'
      fullPath: '/app/medicines/'
      preLoaderRoute: typeof AppMedicinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deliveries/': {
      id: '/app/deliveries/'
      path: '/'
      fullPath: '/app/deliveries/'
      preLoaderRoute: typeof AppDeliveriesIndexRouteImport
      parentRoute: typeof AppDeliveriesRoute
    }
    '/app/tracking/$id': {
      id: '/app/tracking/$id'
      path: '/$id'
      fullPath: '/app/tracking/$id'
      preLoaderRoute: typeof AppTrackingIdRouteImport
      parentRoute: typeof AppTrackingRoute
    }
    '/app/shipments/$id': {
      id: '/app/shipments/$id'
      path: '/$id'
      fullPath: '/app/shipments/$id'
      preLoaderRoute: typeof AppShipmentsIdRouteImport
      parentRoute: typeof AppShipmentsRoute
    }
    '/app/payments/$id': {
      id: '/app/payments/$id'
      path: '/$id'
      fullPath: '/app/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/app/medicines/$id': {
      id: '/app/medicines/$id'
      path: '/medicines/$id'
      fullPath: '/app/medicines/$id'
      preLoaderRoute: typeof AppMedicinesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deliveries/$id': {
      id: '/app/deliveries/$id'
      path: '/$id'
      fullPath: '/app/deliveries/$id'
      preLoaderRoute: typeof AppDeliveriesIdRouteImport
      parentRoute: typeof AppDeliveriesRoute
    }
    '/app/medicines/$id/': {
      id: '/app/medicines/$id/'
      path: '/'
      fullPath: '/app/medicines/$id/'
      preLoaderRoute: typeof AppMedicinesIdIndexRouteImport
      parentRoute: typeof AppMedicinesIdRoute
    }
    '/app/users/pharmacy/$id': {
      id: '/app/users/pharmacy/$id'
      path: '/pharmacy/$id'
      fullPath: '/app/users/pharmacy/$id'
      preLoaderRoute: typeof AppUsersPharmacyIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/users/manufacturer/$id': {
      id: '/app/users/manufacturer/$id'
      path: '/manufacturer/$id'
      fullPath: '/app/users/manufacturer/$id'
      preLoaderRoute: typeof AppUsersManufacturerIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/users/delivery/$id': {
      id: '/app/users/delivery/$id'
      path: '/delivery/$id'
      fullPath: '/app/users/delivery/$id'
      preLoaderRoute: typeof AppUsersDeliveryIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/partners/$type/$id': {
      id: '/app/partners/$type/$id'
      path: '/$type/$id'
      fullPath: '/app/partners/$type/$id'
      preLoaderRoute: typeof AppPartnersTypeIdRouteImport
      parentRoute: typeof AppPartnersRoute
    }
    '/app/medicines/$id/history': {
      id: '/app/medicines/$id/history'
      path: '/history'
      fullPath: '/app/medicines/$id/history'
      preLoaderRoute: typeof AppMedicinesIdHistoryRouteImport
      parentRoute: typeof AppMedicinesIdRoute
    }
  }
}

interface AppDeliveriesRouteChildren {
  AppDeliveriesIdRoute: typeof AppDeliveriesIdRoute
  AppDeliveriesIndexRoute: typeof AppDeliveriesIndexRoute
}

const AppDeliveriesRouteChildren: AppDeliveriesRouteChildren = {
  AppDeliveriesIdRoute: AppDeliveriesIdRoute,
  AppDeliveriesIndexRoute: AppDeliveriesIndexRoute,
}

const AppDeliveriesRouteWithChildren = AppDeliveriesRoute._addFileChildren(
  AppDeliveriesRouteChildren,
)

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppPartnersRouteChildren {
  AppPartnersIndexRoute: typeof AppPartnersIndexRoute
  AppPartnersTypeIdRoute: typeof AppPartnersTypeIdRoute
}

const AppPartnersRouteChildren: AppPartnersRouteChildren = {
  AppPartnersIndexRoute: AppPartnersIndexRoute,
  AppPartnersTypeIdRoute: AppPartnersTypeIdRoute,
}

const AppPartnersRouteWithChildren = AppPartnersRoute._addFileChildren(
  AppPartnersRouteChildren,
)

interface AppPaymentsRouteChildren {
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
}

const AppPaymentsRouteChildren: AppPaymentsRouteChildren = {
  AppPaymentsIdRoute: AppPaymentsIdRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
}

const AppPaymentsRouteWithChildren = AppPaymentsRoute._addFileChildren(
  AppPaymentsRouteChildren,
)

interface AppShipmentsRouteChildren {
  AppShipmentsIdRoute: typeof AppShipmentsIdRoute
  AppShipmentsIndexRoute: typeof AppShipmentsIndexRoute
}

const AppShipmentsRouteChildren: AppShipmentsRouteChildren = {
  AppShipmentsIdRoute: AppShipmentsIdRoute,
  AppShipmentsIndexRoute: AppShipmentsIndexRoute,
}

const AppShipmentsRouteWithChildren = AppShipmentsRoute._addFileChildren(
  AppShipmentsRouteChildren,
)

interface AppTrackingRouteChildren {
  AppTrackingIdRoute: typeof AppTrackingIdRoute
  AppTrackingIndexRoute: typeof AppTrackingIndexRoute
}

const AppTrackingRouteChildren: AppTrackingRouteChildren = {
  AppTrackingIdRoute: AppTrackingIdRoute,
  AppTrackingIndexRoute: AppTrackingIndexRoute,
}

const AppTrackingRouteWithChildren = AppTrackingRoute._addFileChildren(
  AppTrackingRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppUsersDeliveryIdRoute: typeof AppUsersDeliveryIdRoute
  AppUsersManufacturerIdRoute: typeof AppUsersManufacturerIdRoute
  AppUsersPharmacyIdRoute: typeof AppUsersPharmacyIdRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppUsersDeliveryIdRoute: AppUsersDeliveryIdRoute,
  AppUsersManufacturerIdRoute: AppUsersManufacturerIdRoute,
  AppUsersPharmacyIdRoute: AppUsersPharmacyIdRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppMedicinesIdRouteChildren {
  AppMedicinesIdHistoryRoute: typeof AppMedicinesIdHistoryRoute
  AppMedicinesIdIndexRoute: typeof AppMedicinesIdIndexRoute
}

const AppMedicinesIdRouteChildren: AppMedicinesIdRouteChildren = {
  AppMedicinesIdHistoryRoute: AppMedicinesIdHistoryRoute,
  AppMedicinesIdIndexRoute: AppMedicinesIdIndexRoute,
}

const AppMedicinesIdRouteWithChildren = AppMedicinesIdRoute._addFileChildren(
  AppMedicinesIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveriesRoute: typeof AppDeliveriesRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppPartnersRoute: typeof AppPartnersRouteWithChildren
  AppPaymentsRoute: typeof AppPaymentsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShipmentsRoute: typeof AppShipmentsRouteWithChildren
  AppTrackingRoute: typeof AppTrackingRouteWithChildren
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppMedicinesIdRoute: typeof AppMedicinesIdRouteWithChildren
  AppMedicinesIndexRoute: typeof AppMedicinesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveriesRoute: AppDeliveriesRouteWithChildren,
  AppInventoryRoute: AppInventoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppPartnersRoute: AppPartnersRouteWithChildren,
  AppPaymentsRoute: AppPaymentsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShipmentsRoute: AppShipmentsRouteWithChildren,
  AppTrackingRoute: AppTrackingRouteWithChildren,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppMedicinesIdRoute: AppMedicinesIdRouteWithChildren,
  AppMedicinesIndexRoute: AppMedicinesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
